### ISSUE TITLE
Update project to WPILib 2020

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/ShowBot#19]
WPILib 2020 is released along with the 2020 FRC season. We will obviously be using WL2020 in competition so we can't continuously switch back and forth between 2019 and 2020.

**Comment by jon-pun** [comment]
WPILib has a new [process ](https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/importing-gradle-project.html)for updating old projects to WPILib 2020, but also requires that all 3rd party libraries end up being updated and re-imported as well. 

**Also an important note: If you made non-standard updates to the build.gradle, you will need to make those changes again.** I'm not gonna change anything without knowing if we updated the build.gradle or not.
