### ISSUE TITLE
Implement communication with an associated Arduino

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/ShowBot#2]
The normal RSL is alright, but we can do better. I'm currently working on a program for an Arduino to:

1. Flash some LEDs in time with how the normal RSL should (basically a pass-through)
2. Set other LEDs to different colors based on either the status of the RIO or data in the program

**Comment by samollari** [comment]
Maybe when the robot is in forward/backward driving mode, the status LEDs could be either green/red.

**Comment by samollari** [comment]
For now, I am putting this in the Testing column in the Project so we test whether this actually works. Once we verify that it does what it's supposed to, we can move it back to In Progress until issue #1 is closed.
Testing ETA: ~~Tuesday 11/5/19 because of our meeting schedule~~ Tonight

**Comment by samollari** [comment]
I2C isn't working. We'll try Serial over USB and, if *that* doesn't work, we'll resort to PWM or plain digital signals

**Comment by samollari** [comment]
Successfully changed communication to Serial over USB and tested the Arduino part, so if this doesn't work, it's something with the RIO.

**Comment by samollari** [comment]
This is tested and working. Now, we need to implement the status functions in the appropriate places in the code:
- [x] Switching driving modes (or just send a byte of the current mode every time `robotPeriodic` is called)
- [x] (Eventually) When shooting

**Comment by Sky14r** [comment]
Attempted to add requested code after ln.s 59 and 65 as per request. If it suddenly is not doing the thing, it's probably that.

**Comment by samollari** [comment]
Shooting should be working. When we test that and it is confirmed working, we can close the issue

**Comment by samollari** [comment]
`PROBLEM` should be working. When we test that and it is confirmed working, we can close the issue

**Comment by samollari** [comment]
This was tested and verified working (55257c4)
